# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: mysql
#   name: sri-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
#   storageClassName: gp2-retain
#   volumeMode: Filesystem
#   volumeName: sri-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-database-pvc
  namespace: sridevapp
  labels:
    app: mysql
    type: sql-vol
spec:
  storageClassName: sql-storage-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi